#language: python
#python:
#  - "3.7"
language: python
python: 3.7
os: linux
dist: xenial
install:
  - sudo apt-get update || true
  - sleep 10
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create -n test-environment python=$TRAVIS_PYTHON_VERSION -f nrSiCap.yml 
  - source activate test-environment
  - sudo chmod 777 data

script:
- ./retrieve_data.sh
- cd 0-Analysis
- travis_wait 50 py.test
- cd ../1-PRL_Figures
- travis_wait 50 py.test
- cd ../2-Additional_Figures
- travis_wait 50 py.test
- cd ../animated_fits
- travis_wait 50 py.test
